### ISSUE TITLE
Kaputt

### ISSUE THREAD

**Issue by rekasiii** [LeonMT1/CookieTeamServerClient#1]
Funktioniert überall aber nicht im Windows Downloads Verzeichnis von meinem Benutzer :)

**Comment by LeonMT1** [comment]
Immer noch so?
Ich denke der Fehler das die Jarfile nicht benutzt werden kann liegt daran das sich das Programm nicht direkt beendet es ist noch eine gewisse Zeit im taskmanager offen mit der Bezeichnung Python.

**Comment by rekasiii** [comment]
okeeeeeeee
